jobs:
  build:
    name: changelogPrint
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: jdk 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: gradle caching
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      run: ./gradlew changelogPrint
name: changelogPrint
on:
  repository_dispatch:
    types: trigger-ga___changelog-print.yml
