concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    needs: sanityCheck
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install JDK ${{ matrix.distribution }} ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.jre }}
    - continue-on-error: true
      name: gradle caching
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      if: matrix.kind == 'maven'
      name: build (maven-only)
      run: ./gradlew :plugin-maven:build -x spotlessCheck
    - continue-on-error: true
      if: matrix.kind == 'gradle'
      name: build (everything-but-maven)
      run: ./gradlew build -x spotlessCheck -PSPOTLESS_EXCLUDE_MAVEN=true
    - continue-on-error: true
      if: matrix.kind == 'npm'
      name: test npm
      run: ./gradlew testNpm
    - continue-on-error: true
      if: matrix.kind == 'shfmt'
      name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - continue-on-error: true
      if: matrix.kind == 'shfmt'
      name: Install shfmt
      run: 'go install mvdan.cc/sh/v3/cmd/shfmt@${{ matrix.shfmt-version }}

        '
    - continue-on-error: true
      if: matrix.kind == 'shfmt'
      name: Test shfmt
      run: ./gradlew testShfmt
    - continue-on-error: true
      if: always()
      name: junit result
      uses: mikepenz/action-junit-report@v4
      with:
        check_name: JUnit ${{ matrix.kind }} ${{ matrix.jre }} ${{ matrix.os }}
        check_retries: true
        report_paths: '*/build/test-results/*/TEST-*.xml'
    strategy:
      fail-fast: false
      matrix:
        include:
        - jre: 11
          kind: maven
          os: windows-latest
        - jre: 17
          kind: gradle
          os: windows-latest
        - jre: 11
          kind: npm
          os: ubuntu-latest
        - jre: 11
          kind: shfmt
          os: ubuntu-latest
          shfmt-version: v3.8.0
        jre:
        - 11
        - 17
        - 21
        kind:
        - maven
        - gradle
        os:
        - ubuntu-latest
  sanityCheck:
    env:
      buildcachepass: ${{ secrets.BUILDCACHE_PASS }}
      buildcacheuser: ${{ secrets.BUILDCACHE_USER }}
    name: spotlessCheck assemble testClasses
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Install JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: gradle caching
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      name: spotlessCheck
      run: ./gradlew spotlessCheck
    - continue-on-error: true
      name: assemble testClasses
      run: ./gradlew assemble testClasses
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
