jobs:
  build:
    env:
      ORG_GRADLE_PROJECT_gpg_key64: ${{ secrets.GPG_KEY64 }}
      ORG_GRADLE_PROJECT_gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      ORG_GRADLE_PROJECT_nexus_pass64: ${{ secrets.NEXUS_PASS64 }}
      ORG_GRADLE_PROJECT_nexus_user: ${{ secrets.NEXUS_USER }}
      gh_token: ${{ secrets.GH_TOKEN }}
    name: deploy
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: jdk 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: gradle caching
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      name: git fetch origin main
      run: git fetch origin main
    - continue-on-error: true
      if: ${{ github.event.inputs.to_publish == 'all' }}
      name: publish all
      run: './gradlew :changelogPush -Prelease=true --stacktrace --warning-mode all
        --no-configuration-cache

        ./gradlew :plugin-gradle:changelogPush -Prelease=true -Pgradle.publish.key=${{
        secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }}
        --stacktrace --warning-mode all --no-configuration-cache

        ./gradlew :plugin-maven:changelogPush -Prelease=true --stacktrace --warning-mode
        all --no-configuration-cache

        '
    - continue-on-error: true
      if: ${{ github.event.inputs.to_publish == 'plugin-gradle' }}
      name: publish just plugin-gradle
      run: './gradlew :plugin-gradle:changelogPush -Prelease=true -Pgradle.publish.key=${{
        secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }}
        --stacktrace --warning-mode all --no-configuration-cache

        '
    - continue-on-error: true
      if: ${{ github.event.inputs.to_publish == 'plugin-maven' }}
      name: publish just plugin-maven
      run: './gradlew :plugin-maven:changelogPush -Prelease=true --stacktrace --warning-mode
        all --no-configuration-cache

        '
    - continue-on-error: true
      if: ${{ github.event.inputs.to_publish == 'lib' }}
      name: publish just lib
      run: './gradlew :changelogPush -Prelease=true --stacktrace --warning-mode all
        --no-configuration-cache

        '
name: deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
